"""Change User.login to User.mail

Revision ID: bd5c704186b5
Revises: d296f9a22189
Create Date: 2024-04-21 09:57:12.572087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd5c704186b5'
down_revision: Union[str, None] = 'd296f9a22189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'login', nullable=False, new_column_name='mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
